### ISSUE TITLE
Problem when running program

### ISSUE THREAD

**Issue by williamlliiuu** [freyta/7Eleven-Python#34]
Hi I get this problem when I try to run app.py.
`Traceback (most recent call last):
  File "C:\Users\--\7Eleven-Python-master\app.py", line 41, in <module>
    # Used for all of our custom settings and functions
  File "C:\Users\--\7Eleven-Python-master\functions.py", line 22, in <module>
    import pyDes
ModuleNotFoundError: No module named 'pyDes'`
Any help is much appreciated, thanks in advance!

**Comment by NGPriest** [comment]
You're missing pyDes...

**Comment by williamlliiuu** [comment]
How do I get pyDes then? I used to pip install requirements.txt so far but thats it.

**Comment by NGPriest** [comment]
```
C:\Users\NGPriest>python
>>> import pyDes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pyDes

C:\Users\NGPriest>install pyDes
Collecting pyDes
  Downloading https://files.pythonhosted.org/packages/92/5e/0075a35ea5d307a182b0963900298b209ea2f363ccdd5a27e8cb04c58410/pyDes-2.0.1.tar.gz
Installing collected packages: pyDes
  Running setup.py install for pyDes ... done
Successfully installed pyDes-2.0.1

C:\Users\NGPriest>python
>>> import pyDes
>>>
```

**Comment by williamlliiuu** [comment]
```
C:\Users\willi>pip install pydes
Requirement already satisfied: pydes in c:\users\willi\appdata\local\programs\python\python37-32\lib\site-packages (2.0.1)
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
I get this when I try to install it

**Comment by williamlliiuu** [comment]
I uninstalled pydes and reinstalled it with pip, and it still returns with no module found when trying to import pyDes

**Comment by freyta** [comment]
Try installing "pyDes" instead of "pydes".

If that doesn't work, rename the module to pydes in app.py

**Comment by williamlliiuu** [comment]
Okay got that part working now! Sorry but I got another problem, when I try to access the login for locker I get an error:
```
[2019-08-05 18:29:42,117] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\willi\Documents\Programming\7Eleven-Python-master\app.py", line 93, in index
    session['max_price'] = config['General']['max_price']
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'General'
192.168.0.199 - - [05/Aug/2019 18:29:42] "GET / HTTP/1.1" 500 -
192.168.0.199 - - [05/Aug/2019 18:29:42] "GET /favicon.ico HTTP/1.1" 404 -
```
Appreciate your help!

**Comment by freyta** [comment]
I just pushed an update through to fix this. It is because you don't have an autolock.ini file.

Now when you start the script it will check if it exists, if it doesn't it will create it for you.
