### ISSUE TITLE
another login error

### ISSUE THREAD

**Issue by evo87** [freyta/7Eleven-Python#36]
```
[2019-08-19 22:39:04,350] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/adm/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adm/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adm/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/adm/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adm/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 133, in login
    'X-VmobID':functions.des_encrypt_string(session['DEVICE_ID']),
  File "/opt/7Eleven/functions.py", line 265, in des_encrypt_string
    encrypted_message = cipher.encrypt(encryption_prefix + DEVICE_ID)
  File "/home/adm/.local/lib/python2.7/site-packages/pyDes.py", line 655, in encrypt
    data = self._guardAgainstUnicode(data)
  File "/home/adm/.local/lib/python2.7/site-packages/pyDes.py", line 233, in _guardAgainstUnicode
    raise ValueError("pyDes can only work with bytes, not Unicode strings.")
ValueError: pyDes can only work with bytes, not Unicode strings.
```

**Comment by freyta** [comment]
You need to use Python 3, I am no longer supporting Python 2.7
