### ISSUE TITLE
NameError: name 'config' is not defined

### ISSUE THREAD

**Issue by gexd10** [freyta/7Eleven-Python#38]
session['max_price'] = config['General']['max_price']
NameError: name 'config' is not defined

Spend a lot of time to debug. Still not working.

**Comment by NGPriest** [comment]
What's the full error?

**Comment by gexd10** [comment]
@NGPriest 
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-10-26 21:46:34,507] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/Documents/GitHub/711/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Documents/GitHub/711/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Documents/GitHub/711/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Documents/GitHub/711/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Documents/GitHub/711/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Documents/GitHub/711/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Documents/GitHub/711/app.py", line 93, in index
    session['max_price'] = config['General']['max_price']
NameError: name 'config' is not defined
127.0.0.1 - - [26/Oct/2019 21:46:34] "GET / HTTP/1.1" 500 -

**Comment by NGPriest** [comment]
Hmm, did you enable auto locker?
Do you have an autolock.ini?

More questions to come...

**Comment by gexd10** [comment]
> Hmm, did you enable auto locker? Do you have an autolock.ini? More questions to come...

Both yes. 
It is working when I run python app.py. 
But when I use gunicorn, I got this error.

**Comment by NGPriest** [comment]
Keep using python :D

**Comment by gexd10** [comment]
I'd like to deploy on my personal cloud.

**Comment by NGPriest** [comment]
Keep using python?

Please don't tell me your personal cloud doesn't have python...? :S

**Comment by gexd10** [comment]
It does. A personal cloud which I mean Heroku. After I deployed on Heroku, I got the same 500 error.

**Comment by MattKobayashi** [comment]
Why are you trying to run this app in gunicorn? Gunicorn is meant for Python apps that make use of worker microprocesses, which isn't how this app is designed. As NGPriest said, stick to regular Python for this particular app, or run the Docker container version if you want to keep things isolated.

**Comment by gexd10** [comment]
@ingenieurmt 

Coz I'd like to use Web Server Gateway Interface HTTP server, that is why I use gunicorn and deploy on Heroku cloud.

Anyways, thank you for your help.

**Comment by MattKobayashi** [comment]
This might help you with getting Flask working with Gunicorn: https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04

This issue should be closed, it's not a bug with 7Eleven-Python.
