### ISSUE TITLE
Internal Server Error when DEVICE_ID populated

### ISSUE THREAD

**Issue by gyrex** [freyta/7Eleven-Python#43]
Hi guys,

Awesome project and thanks so much for your efforts in putting this together.

I'm successfully running this on a Raspberry PI. However, In order to log in I need to keep the device ID field blank. If the device ID is populated, I get the following error:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by NGPriest** [comment]
An error log might help?

**Comment by gyrex** [comment]
Apologies. Does the application write to syslog or anywhere else other than on-screen?

 * Running on http://0.0.0.0:8181/ (Press CTRL+C to quit)
10.11.12.240 - - [18/Nov/2019 13:23:51] "GET / HTTP/1.1" 200 -
[2019-11-18 13:23:55,725] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 133, in login
    'X-VmobID':functions.des_encrypt_string(session['DEVICE_ID']),
  File "/home/john/7Eleven-Python/functions.py", line 265, in des_encrypt_string
    encrypted_message = cipher.encrypt(encryption_prefix + DEVICE_ID)
  File "/usr/local/lib/python2.7/dist-packages/pyDes.py", line 655, in encrypt
    data = self._guardAgainstUnicode(data)
  File "/usr/local/lib/python2.7/dist-packages/pyDes.py", line 233, in _guardAgainstUnicode
    raise ValueError("pyDes can only work with bytes, not Unicode strings.")
ValueError: pyDes can only work with bytes, not Unicode strings.
10.11.12.240 - - [18/Nov/2019 13:23:55] "POST /login HTTP/1.1" 500 -

**Comment by MattKobayashi** [comment]
Hey @gyrex, looks like you're using Python 2.7. The project now requires Python 3 to run properly. Please update your Python install and try again.

**Comment by gyrex** [comment]
Beautiful! For others who have this issue, I got it working by running the following:

sudo apt-get install python3-pip && sudo -H pip3 install setuptools wheel
python3 app.py
