### ISSUE TITLE
Internal Server Error - Android Phone

### ISSUE THREAD

**Issue by ragz16** [freyta/7Eleven-Python#49]
It used to work fine but lately comes up with Internal Server Error when trying in a web broswer.

Note: You have not set an API key. You will not be able to use Google to find a stores coordinates.
But you can still use the manual search if you know the postcode to the store you want to lock in from.

Note: You have not set a device ID. A random one will be set when you login.
Note: Opening stores.json
Note: Your stores.json file is too old, updating it..
Note: Updating stores.json complete
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [13/Jan/2020 20:28:16] "GET /favicon.ico HTTP/1.1" 404 -
[2020-01-13 20:28:24,620] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 96, in index
    fuelPrice = functions.cheapestFuelAll()
  File "/data/data/com.termux/files/home/7Eleven-python/functions.py", line 96, in cheapestFuelAll
    response = json.loads(r.text)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/_init_.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode

**Comment by freyta** [comment]
It's been discussed before.  Issue #45 discusses it and [this](https://github.com/freyta/7Eleven-Python/commit/161c4841c28225af96f166f9bd3bb9296dc6a916) commit fixed it. You need to update your files.
